#ENC[AES256_GCM,data:qgD1oDPMRyd5AmzApvBUPbppuMXgNqihT/hw9ziQRlwT19iLu5z457zxdg7YnmO4MJjLKZ0mL4nYBVL7WbD1Ip6Wx/wP7qGW,iv:aYuICI+vHp1Hlg4G4WUZ22L9Wp6S4bwUUHo4t8aJi4A=,tag:py+BVPksT/SUMA5vy3esYw==,type:comment]
#ENC[AES256_GCM,data:rtEhijWZv4F2o2BF0HjRmiSP7SOG1j4/ik2tBD+QJ5idrTByFkRk+6LDCtZ46d6HPP96+WA1H9k3l/vN2uQ=,iv:Wyz1WQXBAcLs8BuQEv7a7agvW3ukHQMF/SEo4eZdyoQ=,tag:aVQxiTSt1qgsfVdvLo8k2g==,type:comment]
#ENC[AES256_GCM,data:C/NwZRh4rK1NRAo/zzoqxSwOGg7dxZRNvSIUCeJeP1ohCgoL5fJXXDA5T6umyQsPW2lgyyXfOpqC7eE=,iv:Jv1iWFXyIDVdwMRuCRTG4gjVFqyAo66FtWu6xSJO8+U=,tag:qf+qsKOZoWudBf7SzD5bTA==,type:comment]
apiVersion: ENC[AES256_GCM,data:VOg=,iv:0NEChGitbMJomDgbvbX/DTuKpzo8PvwakTaDE5pKAEg=,tag:yvOVNCh1XI0hTB/m4e/t4g==,type:str]
kind: ENC[AES256_GCM,data:zdv3ZVax,iv:7+D6kPgudm1z1KA5INOekBci7WqehY+TwnIqn+ZxR3E=,tag:oEuR0skNAkc2cQ8QhInBiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tOnIgOzQfHw6MI8X5Q==,iv:EmCbYjFTSeoYteCEruDeDIe4XxxOgFhaoUY+KId7X1Q=,tag:dTA7dFc5LaiwgXs1gPqjtw==,type:str]
    namespace: ENC[AES256_GCM,data:M05Fs8eZZKg=,iv:s2AdunMyZBHnnH3lD2HU4y2rWujBoGi+WbVjb0zZH0s=,tag:n7N7RSPpEm4gVtsJ7N56QQ==,type:str]
type: ENC[AES256_GCM,data:zAgup46B,iv:s4gmgziPcxJWaN3B881zOvC1C3FyAoALJSgqOS095hg=,tag:u5r42cHVF8YjdSZpyaEQXg==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:c9eSj2Tb58w=,iv:BoYwbUoBUap9SpvKacc++ATZEKuAfJ9QpxPc9kHDi5g=,tag:8fOD2tPaHGwzO8qz7aRETQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:LA+L2la9jiNppfPqxQR0s+JnMfWf/WZo638vEKtxtForX1fqVxMvhQ==,iv:53uydj/oQ3qvB0y2bRENrN6YwEaZfelKKsnLhS5Wp0k=,tag:xNj/zVWlVjjLvADRrrsU2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ0VORjV3SUdEd0ErR1VR
            YXlCYnVsdk9CUUEwdUZGbWVYK25sU0dmMkhjCmNVbGFMRG5mYW1UNE8yQkRDQkNu
            MzVyTU4wWkh4dnltTUV0UUZIRnU1VmsKLS0tIHU0OVFHbGd1SlhxN0lGOEcxVUhs
            VkFIcnV1aHJiN3ZUTk9aUjVrWHpCa28Kt96iNpKBVxXGvpfbAyYapJANx6Qxvv35
            C787xRDrm5F9M2L7e15JMXwxgSG/FYaPDdCpYR0Tv1XlL7EiZ4uxVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ntg0e9tapq5g7tnrlq8d7wu9z7cptze5hsvh3m6mz68pfpkz4d3qp08t57
    lastmodified: "2026-05-15T12:32:12Z"
    mac: ENC[AES256_GCM,data:o1WFYzp/4JE3xgP42vbhD9Q8o/PotNpGz4N2jBZzxqkBgnuomknc76LuQZ0hxflkgW8r+yKXDXZ6/xoAPy9ZQ3vGkysMKr3aNqn3wXMhQihle8iUMLBIdXbcuCj0nTvXB90ntARkfj0h8Fgy066MsbWq7X1WZY5uVFGnkK67YbI=,iv:yY58zc2p1nSkXT5p21mLf0FyfQNWpODSCfIDlbgA/m4=,tag:gXkV/8CJ6fXdk7uMB7J2Ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
