#ENC[AES256_GCM,data:aKpMoK0U4pZHQO8RfvEpYJ2PyiwtiEQRbBQ9GwLhwqMWMrahVFLe8AittPyr/h8/oZg2KYeTCXKDQqC0QJOAEMS7mg==,iv:P79F+elrzSmpkyAavmpxuoOoGtjfYm0HXYYB7jRu2a8=,tag:3j4s0pALwbTUlpVRn9LE+w==,type:comment]
#ENC[AES256_GCM,data:NKShsPEjnfB9bZ0NbOgzBB3GWMlkR9CsiHEH4w2IGLjsOXJeNuJ7NjnWal4AYplngUjs/QEYfLO89wgq1mMDiY/T,iv:5KTAT+bd2WOWKQZ6kVWulddbDySMLh9Sz990xku76do=,tag:fMz0D0J4/xOZGVsBABgfLw==,type:comment]
#ENC[AES256_GCM,data:/McG30sjjAkNSQZCKdKyuEfaFkgWYAE7+8qp2ZRl,iv:/PJWKHN5oM/ySrphY6FEkNpNQZ/qiWsmiC3eQZnnucw=,tag:97w4fn42FQggMdTfKflFMA==,type:comment]
apiVersion: ENC[AES256_GCM,data:90c=,iv:+ZlBM5142+jO4YSt3jwjFZKAvuXeQj5iL8LWsdQaOK0=,tag:FOZHVSmE/LID+CbpgiCIQA==,type:str]
kind: ENC[AES256_GCM,data:wNKEyVOD,iv:06e/v6nWy0Id/fh1+ti+HmwabWhZfE6bySvVeI1ww44=,tag://NvaxITBFTQdRHpu8uQ4A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kDckEO65G3RrM/nySI68rodRSto=,iv:Pu/9Ty1XzbIZeN04LMHpn6NHSBJlNXbPQpkXD8W+6gU=,tag:KPMcYzKkvIxAsebyQplClg==,type:str]
    namespace: ENC[AES256_GCM,data:n71CKqRjlj7ZqFzi,iv:Hv3CBmLoQUtL8UEwzhIwK4YxJi4U1Z7WXgZfLoVUHEI=,tag:dBaupcHa6vKKgDko0G6f6A==,type:str]
type: ENC[AES256_GCM,data:pA1lItm3,iv:laTZNk01Qe3T7Dn6OcSHqaE+Fkp0+MJPLt0wYdtEB3I=,tag:NRnJVWYfVrlCmBDw4+M0qQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:acjp4aRJUB2tlDwchq4wpjdp+y2ngwwYslQqtu7VCbf7A9urB4V8g85nn+14hfQroKKuSPI=,iv:G7pTcFPy4sIpkdmAMAfppMFHi1OYFLRi5I80IRn8vQw=,tag:3gMy0Ys5N7fXXFlbGXD48g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMUlFTGJMcGJ1RlhYbDBj
            YlJwKzRUQnFwOGtpek14dm9QR1FJSks2YmlVCm8zU24reUlSb2RRd0tVdUlkZkVH
            ZGtLTHN1SVo0UWhXc0YrcE5DVjJQNUkKLS0tIHNJUXZWaWdkZ1pEWkMwMnVMZjJw
            V3g3UU9HYWRlSVBVTzZvYVBCUGdITXcKoitFhgeWg7zMi9PL0lQflJmQfZITf5Kq
            h5rvJVeM7tV5882YqiY1MtE28BlS5j1OYdsJFVZAOOLLNLMjXZg2tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ntg0e9tapq5g7tnrlq8d7wu9z7cptze5hsvh3m6mz68pfpkz4d3qp08t57
    lastmodified: "2026-05-15T12:32:12Z"
    mac: ENC[AES256_GCM,data:8EtyMOW6BiDcFfE1yRQI/y2bIt9GLKtZCuCHUW6cr1FZtSOKDk+s1ox8a0Byh4tCeymwiia34Gzh8DXx5Ol7VftjKJUfNkM7seQQdGFam4ELU/CZdD33dxPWsSs661iIYZI+TfsO5na+WloDSPClf/jYly/ecuCaxkhsySYfcSA=,iv:vy69y1D2eVKwgvJkhDsDA5poMH6Bu42BdOEsTvmezMI=,tag:yTCzd9d4DIapv1QbEp3GPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
